#---------------------------
#FlaskPipeline Project
#Created by Matvey Guralskiy
#---------------------------
version: '3.8'

services:
  flaskpipeline:
    build: .
    image: flask-pipeline:V7.0
    ports:
      - "80:80"
    env_file:
      - .env
