#---------------------------
# FlaskPipeline Project
# Created by Matvey Guralskiy
#---------------------------
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: flaskpipeline-project
  annotations:
  labels:
    env: Production
    type: Website
    owner: Matvey_Guralskiy
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
