apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: FlaskPipeline-Cluster
  region: us-east-1

vpc:
  id: PLACEHOLDER_VPC_ID
  subnets:
    public:
      - PLACEHOLDER_PUBLIC_SUBNET_1_ID
      - PLACEHOLDER_PUBLIC_SUBNET_2_ID

nodeGroups:
  - name: worker-node-1
    instanceType: t3.micro
    desiredCapacity: 2
    securityGroups:
      - PLACEHOLDER_EKS_SG_ID

  - name: worker-node-2
    instanceType: t3.micro
    desiredCapacity: 2
    securityGroups:
      - PLACEHOLDER_EKS_SG_ID